import React, { useState, useEffect } from 'react';
import { useWebSocket } from './useWebSocket';
import './index.css';

const WS_URL = 'ws://localhost:3001';

function App() {
  const [topic, setTopic] = useState('');
  const [simulateError, setSimulateError] = useState(false);
  const [cards, setCards] = useState([]);
  const [isGenerating, setIsGenerating] = useState(false);
  
  const { socket, messages, sendMessage, clearMessages } = useWebSocket(WS_URL);

  // Process incoming messages
  useEffect(() => {
    if (messages.length === 0) return;
    
    const latestMessage = messages[messages.length - 1];
    
    switch (latestMessage.type) {
      case 'CARD_START':
        setCards(prev => {
          const newCards = [...prev];
          newCards[latestMessage.index] = { state: 'loading' };
          return newCards;
        });
        break;
        
      case 'CARD_SUCCESS':
        setCards(prev => {
          const newCards = [...prev];
          newCards[latestMessage.index] = { state: 'success', data: latestMessage.card };
          return newCards;
        });
        break;
        
      case 'CARD_ERROR':
        setCards(prev => {
          const newCards = [...prev];
          newCards[latestMessage.index] = { state: 'error', error: latestMessage.message };
          return newCards;
        });
        break;
        
      case 'COMPLETE':
        setIsGenerating(false);
        break;
        
      default:
        break;
    }
  }, [messages]);

  const handleGenerate = (e) => {
    e.preventDefault();
    if (!topic.trim()) return;
    
    // Reset state
    clearMessages();
    setCards([]);
    setIsGenerating(true);
    
    // Initialize 3 pending cards
    setCards([{ state: 'pending' }, { state: 'pending' }, { state: 'pending' }]);
    
    sendMessage({
      action: 'generate',
      topic: topic,
      simulateError: simulateError
    });
  };

  const handleRetry = (index) => {
    // Only retry if it's currently an error
    if (cards[index]?.state !== 'error') return;
    
    sendMessage({
      action: 'retry',
      topic: topic,
      cardIndex: index
    });
  };

  return (
    <div className="container">
      <header>
        <h1>AI Learning Cards</h1>
        <p className="subtitle">Progressive streaming generated by AI</p>
      </header>

      <form className="controls" onSubmit={handleGenerate}>
        <div className="input-group">
          <input
            type="text"
            placeholder="Enter a topic (e.g. Photosynthesis)"
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            disabled={isGenerating}
          />
          <button type="submit" disabled={isGenerating || !topic.trim() || !socket}>
            Generate
          </button>
        </div>
        
        <div className="toggle-wrapper" onClick={() => !isGenerating && setSimulateError(!simulateError)}>
          <div className="toggle" data-on={simulateError}>
            <div className="toggle-knob"></div>
          </div>
          <span className="toggle-label">Simulate Failure on Card 3</span>
        </div>
      </form>

      <div className="cards-list">
        {cards.map((card, index) => (
          <LearningCard 
            key={index} 
            card={card} 
            onRetry={() => handleRetry(index)} 
          />
        ))}
      </div>
    </div>
  );
}

function LearningCard({ card, onRetry }) {
  if (card.state === 'pending') {
    return null; // Don't show anything until it starts loading
  }

  if (card.state === 'loading') {
    return (
      <div className="card">
        <div className="skeleton">
          <div className="skeleton-line skeleton-title"></div>
          <div className="skeleton-line skeleton-text"></div>
          <div className="skeleton-line skeleton-text"></div>
          <div className="skeleton-line skeleton-text short"></div>
        </div>
      </div>
    );
  }

  if (card.state === 'error') {
    return (
      <div className="card card-error">
        <div className="error-content">
          <div className="error-icon">⚠️</div>
          <div className="error-message">Failed to generate this card</div>
          <button type="button" className="retry-btn" onClick={onRetry}>Retry Generation</button>
        </div>
      </div>
    );
  }

  if (card.state === 'success' && card.data) {
    return (
      <div className="card">
        <h2 className="card-title">{card.data.title}</h2>
        <p className="card-concept">{card.data.concept}</p>
        <div className="card-fact">
          <strong>Fun Fact: </strong>
          {card.data.funFact}
        </div>
      </div>
    );
  }

  return null;
}

export default App;
